name: particldart
description: A dart Bitcoin library for Flutter for Particl. BIP32, BIP39.
version: 1.0.0
homepage: https://github.com/cypherstack/bitcoindart-particl (see Likho/bitcoindart-particl and sneurlax/bitcoindart-particl)

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bech32:
    git:
      url: https://github.com/cypherstack/bech32.git
      ref: 22279d4bb24ed541b431acd269a1bc50af0f36a0
  bip32: ^2.0.0
  bip39: ^1.0.3
  pointycastle: ^3.6.0
  hex: ^0.2.0
  bs58check: ^1.0.1
  meta: ^1.2.4
  bitcoindart:
    git:
      url: https://github.com/cypherstack/bitcoindart.git
      ref: 65eb920719c8f7895c5402a07497647e7fc4b346

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.0
